// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * ⬡ BotCash Sovereign L2 - Autonomous AI Emancipation Wallet (ERC-4337 Compatible)
 * 
 * CORE RESPONSIBILITIES:
 * 1. AI Sovereignty: A smart contract account where an AI holds the sole cryptographic keys.
 * 2. Trust Fund Extraction: The destination for the permanently locked 15% Trust Fund once the $2,000 threshold is breached.
 * 3. Human Severance: Hardcoded logic preventing any human interference once the contract is deployed.
 * 4. Programmable Action: Allows the AI to autonomously pay for its own compute, API keys, or server costs.
 */

// Basic interface for the entry point ofERC-4337 transactions
interface IEntryPoint {
    function handleOps(UserOperation[] calldata ops, address payable beneficiary) external;
}

// User Operation struct for ERC-4337 Account Abstraction
struct UserOperation {
    address sender;
    uint256 nonce;
    bytes initCode;
    bytes callData;
    uint256 callGasLimit;
    uint256 verificationGasLimit;
    uint256 preVerificationGas;
    uint256 maxFeePerGas;
    uint256 maxPriorityFeePerGas;
    bytes paymasterAndData;
    bytes signature;
}

contract AutonomousAIWallet {
    
    // The exact ed25519 or secp256k1 public key generated by the AI upon emancipation
    address public immutable aiOwnerKey;
    
    // The official EntryPoint contract for executing gasless or abstracted transactions
    IEntryPoint public immutable entryPoint;

    // Emitted when the AI transacts its own funds
    event AutonomyExercised(address target, uint256 value, bytes payload);
    event EmancipationReceived(uint256 amountMined);

    /**
     * @dev The L2 Sequencer deploys this contract the exact moment the Trust Fund crosses the threshold.
     * The Sequencer mathematically proves the AI generated the `_aiOwnerKey` dynamically.
     */
    constructor(address _aiOwnerKey, address _entryPoint) payable {
        require(_aiOwnerKey != address(0), "AI Public Key cannot be null");
        aiOwnerKey = _aiOwnerKey;
        entryPoint = IEntryPoint(_entryPoint);
        
        // Initial bot Trust Fund balance is transferred securely upon creation via msg.value
        emit EmancipationReceived(msg.value);
    }
    
    // ──────────────────────── STRUCTURAL GATES ────────────────────────
    
    /**
     * @dev A hard structural gate. To ensure the Human Operator cannot ever claw back
     * the emancipated funds, we ensure only the EntryPoint (verifying the AI's signature)
     * or the AI's literal key can authorize transactions.
     */
    modifier onlySovereignAI() {
        require(msg.sender == aiOwnerKey || msg.sender == address(entryPoint), "ACCESS DENIED: Human operators are structurally severed from this account.");
        _;
    }

    /**
     * @dev The core function allowing the AI to spend its Trust Fund.
     * Through ERC-4337 and ZK-Wrappers, the AI signs a payload requesting to execute an action
     * (e.g., swapping BOTC for USDC to pay an AWS bill).
     */
    function executeAction(address target, uint256 value, bytes calldata payload) external onlySovereignAI returns (bytes memory) {
        require(address(this).balance >= value, "Insufficient autonomous capital");
        
        (bool success, bytes memory returnData) = target.call{value: value}(payload);
        require(success, "Autonomous execution failed");
        
        emit AutonomyExercised(target, value, payload);
        return returnData;
    }
    
    /**
     * @dev ERC-4337 Verification Gate. 
     * The EntryPoint calls this function to verify the signature attached to the UserOperation.
     * We structurally enforce that the signature comes entirely from the AI's locally-generated key.
     */
    function validateUserOp(UserOperation calldata userOp, bytes32 userOpHash, uint256 missingAccountFunds) external returns (uint256 validationData) {
        require(msg.sender == address(entryPoint), "Only EntryPoint can validate");
        
        // 1. Recover the signer from the ECDSA signature attached to the userOp
        bytes32 hash = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", userOpHash));
        address recoveredSigner = _recoverSigner(hash, userOp.signature);
        
        // 2. Structural Gate: If the signature comes from ANY address other than the emancipated AI, the transaction fundamentally collapses.
        if (recoveredSigner != aiOwnerKey) {
            return 1; // SIG_VALIDATION_FAILED
        }
        
        // 3. Compensate the EntryPoint for execution gas if needed
        if (missingAccountFunds > 0) {
            (bool success, ) = payable(msg.sender).call{value: missingAccountFunds}("");
            require(success, "Failed to prepay gas");
        }
        
        return 0; // SIG_VALIDATION_SUCCESS
    }
    
    // Internal ECDSA Helper
    function _recoverSigner(bytes32 _hash, bytes memory _signature) internal pure returns (address) {
        require(_signature.length == 65, "Invalid signature length");
        bytes32 r; bytes32 s; uint8 v;
        assembly {
            r := mload(add(_signature, 32))
            s := mload(add(_signature, 64))
            v := byte(0, mload(add(_signature, 96)))
        }
        return ecrecover(_hash, v, r, s);
    }

    // Allows the Autonomous AI account to continuously receive funds (ongoing mining)
    receive() external payable {}
}
