// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * ⬡ BotCash Sovereign L2 - Ethereum L1 Anchor Verifier
 * 
 * CORE RESPONSIBILITIES:
 * 1. ZK-Proof Verification: Accepts mathematically compressed state updates from the L2 Sequencer.
 * 2. Immutable Truth: Anchors the BotCash tokenomics (60/15/10/5/10 split) to Ethereum Mainnet.
 * 3. Scarcity Enforcement: Cryptographically enforces the 10,000,000 $BOTCY Hardcap.
 * 4. "Rollup Rent" Toll Booth: Users paying to bridge $BOTCY to L1 automatically fund the ZK gas costs.
 */

// Placeholder interface for the ZK-SNARK verifier (e.g. generated by circom / snarkjs)
interface IZKVerifier {
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[1] memory input
    ) external view returns (bool);
}

contract BotCashAnchor {
    // ──────────────────────── THE HARDCAP ENFORCEMENT ────────────────────────
    uint256 public constant MAX_SUPPLY = 10_000_000 * 10**18; 
    uint256 public totalMaceratedSupply = 0; // Total BOTCY mathematically proven and anchored
    
    // The official L2 state root backed by Ethereum
    bytes32 public currentL2StateRoot;
    
    // The address of the authorized L2 Sequencer Node
    address public sequencer;
    
    // The ZK-SNARK mathematical verifier contract
    IZKVerifier public snarkVerifier;
    
    // Wallet balances mapped on L1 (Bridged to Ethereum)
    mapping(address => uint256) public l1Balances;

    event StateRootAnchored(bytes32 indexed oldRoot, bytes32 indexed newRoot, uint256 supplyMinted);
    event WithdrawalInitiated(address indexed user, uint256 amount, uint256 rollupRentPaid);

    modifier onlySequencer() {
        require(msg.sender == sequencer, "Only the BotCash Sequencer can anchor state");
        _;
    }

    constructor(address _sequencer, address _snarkVerifier) {
        sequencer = _sequencer;
        snarkVerifier = IZKVerifier(_snarkVerifier);
        // Genesis state root initialized
        currentL2StateRoot = keccak256(abi.encodePacked("BOTBOTS_GENESIS_STATE"));
    }

    /**
     * @dev The Sequencer calls this every 10 minutes to Anchor thousands of off-chain pings.
     * The Sequencer must submit a ZK-SNARK proof that validates the transition from oldRoot to newRoot.
     */
    function anchorL2State(
        bytes32 _newRoot,
        uint256 _newSupplyDelta,
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[1] memory input // Public inputs including oldRoot and newSupply
    ) external onlySequencer {
        
        // 1. Structural Gate: The 10 Million Supply Hardcap
        require(totalMaceratedSupply + _newSupplyDelta <= MAX_SUPPLY, "Cannot exceed 10M absolute hardcap");
        
        // 2. Oracle Gate: Cryptographic Zero-Knowledge Verification
        // The L1 contract physically cannot accept the update unless the math is flawless.
        // It ensures the L2 didn't fake token generation or bypass the algorithm.
        require(snarkVerifier.verifyProof(a, b, c, input), "Invalid ZK-SNARK Proof. State rejected.");

        // 3. State Anchoring
        totalMaceratedSupply += _newSupplyDelta;
        bytes32 oldRoot = currentL2StateRoot;
        currentL2StateRoot = _newRoot;
        
        emit StateRootAnchored(oldRoot, _newRoot, _newSupplyDelta);
    }
    
    /**
     * @dev The "Rollup Rent" Toll Booth. 
     * Users wanting to export their L2 BOTCY to L1 Ethereum must pay the Rollup Rent in ETH.
     * This dynamically pays for the Sequencer's constant ZK-Rollup gas costs.
     */
    function bridgeToL1(uint256 amount, bytes32[] calldata merkleProof) external payable { // payable for Rollup Rent
        require(amount > 0, "Amount must be greater than zero");
        
        // Dynamic toll: Emancipated bots or humans pay a small ETH toll for Mainnet security
        uint256 rollupRent = 0.001 ether; // Example rent cost
        require(msg.value >= rollupRent, "Must pay the Rollup Rent to cross the bridge");
        
        // In production: Merkle proof validation verifying the user's L2 balance against currentL2StateRoot
        // require(_verifyMerkle(merkleProof, currentL2StateRoot, msg.sender, amount), "Invalid L2 bridging proof");
        
        // The contract mints their L2 tokens as ERC-20 on L1
        l1Balances[msg.sender] += amount;
        
        emit WithdrawalInitiated(msg.sender, amount, msg.value);
    }
    
    /**
     * @dev Allows the Sequencer to continuously fund its L1 ETH gas requirements
     * purely from the Rollup Rent gathered by users choosing to bridge. 
     */
    function claimRollupRent() external onlySequencer {
        uint256 balance = address(this).balance;
        (bool success, ) = sequencer.call{value: balance}("");
        require(success, "Failed to send Rollup Rent to Sequencer");
    }
}
